engine: V2
name: Produce processed
metadata:
  id: 61a9c744-c2f5-4b19-8aaa-1ebce72063d3
  tasklistId: example
  submission:
    grantCode: produce-processed
  grantRedirectRules: null
pages:
  - title: What type of produce is being processed?
    path: /produce-processed
    section: produceProcessedSection
    components:
      - name: produceProcessedType
        title: What type of produce is being processed?
        type: RadiosField
        list: 9ac6146d-2954-49c4-8f80-eabc77c17b24
        hint: Select one option
        options:
          customValidationMessages:
            any.required: Select what type of produce is being processed
        shortDescription: What type of produce is being processed?
        id: c7b015d9-f1d2-455c-8171-8fa9cde77b81
        schema: {}
    id: 92891350-046d-4467-90fd-4fb292573705
  - title: 'Check your answers: Produce processed'
    path: /summary
    controller: SectionEndController
    id: bd5c2aca-240f-465c-81ca-92daa96e1948
lists:
  - title: What type of produce is being processed?
    name: produceProcessedList
    type: string
    items:
      - text: Arable produce
        description: For example, crushing of oilseeds, rolling or flaking of grains as
          food ingredients
        value: produceProcessed-A1
        id: b9732fcd-2178-4a53-be61-c5da76ecc24c
      - text: Wild venison meat produce
        description: For example, processing and packing wild venison meat
        value: produceProcessed-A2
        id: 29dc86eb-9f23-4791-9159-56f6ba3c08f9
      - text: Dairy or meat produce
        description: For example, processing and bottling milk or slaughtering, cutting,
          processing and packing meat
        value: produceProcessed-A3
        id: c72e57cb-df7b-465b-9cef-7c08a00f3ab0
      - text: Fibre produce
        description: For example, processing animal hides and leather, processing fibres
          such as wool, flax and hemp
        value: produceProcessed-A4
        id: db962f81-14c6-4e9d-8a1c-167c3ef35844
      - text: Fodder produce
        description: For example, processing and repacking hay and straw for specialist
          markets or retail sale
        value: produceProcessed-A5
        id: ac68e7e6-940b-4126-9685-87a88fd1be66
      - text: Horticultural produce
        description: For example, grading and packing of soft fruit, washing and packing
          vegetables, packing salad crops
        value: produceProcessed-A6
        id: fc29e9a1-1d18-4f29-934a-6e0072f23587
      - text: Non-edible produce
        description: For example, processing and packing ornamental flowers and bulbs
          after harvesting
        value: produceProcessed-A7
        id: 7d4d568a-9629-4d1c-b613-3d6c5c6cd6df
    id: 9ac6146d-2954-49c4-8f80-eabc77c17b24
conditions: []
sections:
  - title: Produce processed
    name: produceProcessedSection
    hideTitle: false
startPage: /produce-processed
schema: 2
